the 0-add_integer test file
===============================
import-module 0-add_integer.txt
===============================
>>> add_integer = __import__("0-add_integer").add_integer

===============================
        Test Cases            #
===============================

-------------------Numbres---------------

>>> add_integer(2, 6)
8

>>> add_integer(-2, -6)
-8

>>> add_integer(2, -6)
-4

>>> add_integer(5)
103

>>> add_integer(-1)
97

>>> add_integer(1, )
99

>>> add_integer(1, 0.5)
1

>>> add_integer(1, -0.5)
1

>>> add_integer(0.1, 2.5)
2

>>> add_integer(0.1, -2.5)
-2

>>> add_integer(-1.1, -2.5)
-3

---------------- Checking Not Passed Values ------------------
>>> add_integer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add_integer() missing 1 required positional argument: 'a'

------------------- Checking Strings -----------------------------------
>>> add_integer("e", 5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 11, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer

>>> add_integer(5, "e")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 13, in add_integer
    raise TypeError("b must be an integer")
TypeError: b must be an integer

>>> add_integer("e")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/alx-higher_level_programming/0x07-python-test_driven_development/0-add_integer.py", line 11, in add_integer
    raise TypeError("a must be an integer")
TypeError: a must be an integer

------------------------Ø¢Name--------------------------------------
>>> add_integer(e)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'e' is not defined



